# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Personal Demographics Service (PDS) API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "{VERSION}"
  title: Personal Demographics Service (FHIR) API
  description: |
    ## Overview
    Use this API to access the [Personal Demographics Service (PDS)](https://digital.nhs.uk/services/demographics) - the national electronic database of NHS patient details such as name, address, date of birth and NHS Number.

    You can:
    * search for patients
    * get patient details
    * get patient related people

    You cannot currently use this API to:
    * check that you have the right NHS Number for a patient
    * update patient details (coming soon)
    * create a new record for a birth
    * receive birth notifications
    * create a record for a new patient
    * register a new patient at a GP Practice - instead, use [National Health Application and Infrastructure Services (NHAIS)](https://digital.nhs.uk/services/nhais/nhais-developer-document-library)

    You can access the following data:
    * NHS Number
    * name
    * gender
    * addresses and contact details
    * birth information
    * death information
    * registered GP
    * nominated pharmacy
    * dispensing doctor pharmacy
    * medical appliance supplier pharmacy
    * related people
    * consent information (coming soon)

    Currently, this API can only be accessed by healthcare professionals, authenticated with an NHS smartcard or equivalent.
    Unauthenticated access and citizen access are on the roadmap.

    ## Legal use
    This API can only be used where there is a legal basis to do so. You should [make a PDS access request](https://digital.nhs.uk/services/demographics/access-data-on-the-personal-demographics-service) before you go too far with your development.
    
    You must have made this request before you can go live (see ‘Onboarding’ below).

    ## Related APIs
    The following APIs also give access to the Personal Demographics Service:
    - [Personal Demographics Service (SMSP) API](https://digital.nhs.uk/developer/api-specifications/personal-demographics-service---smsp-api) - use this if you want to get PDS data without an authenticated end used (no smartcard required). It is, however, read-only and searches are limited to a single result.
    - [Personal Demographics Service (HL7 V3) API](https://digital.nhs.uk/developer/api-specifications/personal-demographics-service-hl7-v3) - use this if you want to use functions that are not yet available on the FHIR API.

    Once our roadmap is complete, the above APIs will become redundant.

    The following APIs are also related to this API:
    - [Organisation Data Service FHIR API](https://developer.nhs.uk/apis/ods/) - use this to get full details for the organisations related to the patient, such as their registered GP or nominated pharmacy.

    ## API status and roadmap
    The search and retrieve endpoints are in [beta](https://digital.nhs.uk/developer/developer-reference/reference-guide#api-status), meaning:
    - we might make breaking changes, but only if we can't avoid it, and we'll give advance notice
    - we can't guarantee availability or performance

    The update endpoint is in [alpha](https://digital.nhs.uk/developer/developer-reference/reference-guide#api-status) - expect further breaking changes.

    The API is currently available for sandbox testing and integration testing, but not for production use.

    The following items are on our roadmap, in rough priority order:
    - integration testing service - enhancement to support authorisation with NHS smartcards (target date: ASAP)
    - production service - beta - search for patient and retrieve patient details (target date: end of April 2020)
    - addition of data fields for consent information
    - production service - beta - update patient (target date: end of May 2020)
    - unauthenticated access - without NHS smartcard - similar to the PDS SMSP API (target date to be confirmed - please [contact us](https://digital.nhs.uk/developer/help-and-support) for more details)
    - access for citizens using NHS Login (target date to be confirmed - please [contact us](https://digital.nhs.uk/developer/help-and-support) for more details)
    - exit beta (target date: end of September 2020, subject to availability of beta testers)

    We are extremely keen to receive feedback on the API during beta,
    for example if there are data fields missing that you think you need.
    Please [contact us](https://digital.nhs.uk/developer/help-and-support) with any comments or suggestions.

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/developer-reference/introduction-to-apis#basic-rest).

    It also conforms to the [FHIR](https://digital.nhs.uk/developer/developer-reference/introduction-to-apis#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.

    You don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, for example the `/Patient` not `/patients`
    - array names are singular, for example `line` not `lines` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    This API is available on the Internet, although access using NHS smartcards (see below)
    currently requires a connection to the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    ## Authorisation
    This API is [user-restricted](https://digital.nhs.uk/developer/developer-reference/security-and-authorisation#user-restricted-apis),
    meaning an end user must be present and authenticated to use it.

    The end user must be:
    - a healthcare professional
    - strongly authenticated, using either an NHS smartcard or a modern alternative

    The API uses Open ID Connect to authenticate the end user and OAuth 2.0 to authorise the calling system.
    It supports the following security patterns:
    * user-restricted RESTful API - using NHS Identity - combined authentication and authorisation
    * user-restricted RESTful API - using NHS Identity - separate authentication and authorisation

    For more details, see [user-restricted APIs](https://digital.nhs.uk/developer/developer-reference/security-and-authorisation#user-restricted-apis).

    In due course we plan to add the following:
    - access for citizens, using NHS Login
    - unattended access - without smartcard - similar to the PDS SMSP API

    ## Environments and testing

    | Environment       | Base URL                                                       |
    | ----------------- | -------------------------------------------------------------- |
    | Sandbox           | `https://sandbox.api.service.nhs.uk/personal-demographics/`    |
    | Integration test  | `https://int.api.service.nhs.uk/personal-demographics/`        |
    | Production        | Not yet available                                              |

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/developer-reference/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is stateless, so it does not actually persist any updates
    * is open access, so does not allow you to test authorisation

    For more details on sandbox testing, or to try out the sandbox using our "Try this API" feature, see the documentation for each endpoint.

    Alternatively, you can try out the sandbox using our Postman collection:

    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/dc052f444e70d072e577)

    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/developer-reference/testing#integration-testing):
    * is for formal integration testing
    * includes authorisation, although at the moment it only supports signing in with a user name and password - authorisation with smartcards is coming soon

    You can use our [PDS FHIR API test data pack](https://digital.nhs.uk/developer/api-specifications/pds-fhir-api-test-data) to test most common scenarios. You can also create your own test data.

    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/developer-reference/testing#integration-testing-with-our-restful-apis).

    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.
    
    To onboard for this API, follow the [Supplier Conformance Assessment List (SCAL) process.](https://digital.nhs.uk/developer/developer-reference/onboarding-process#onboard-using-the-supplier-conformance-assessment-list-scal-process)

    When following the SCAL process, note that:
    * In step 1: to confirm your use case for this API, you need to [make a PDS access request](https://digital.nhs.uk/services/demographics/access-data-on-the-personal-demographics-service), even if you already access PDS via another method.
    * In step 6: when implementing your clinical risk management process, you must review and integrate the PDS FHIR API hazard log into your own risk log. You’ll find it embedded within the PDS FHIR API tab in the SCAL.
    * In step 8: you need to review and complete the PDS FHIR API risk log to show that you have understood and mitigated the various risks. You might be asked to provide some evidence to prove that controls have been put in place. You’ll find the risk log embedded within the PDS FHIR API tab in the SCAL. This is separate from the clinical safety hazard log mentioned above.
    * In step 9: you must conduct penetration testing to [CHECK standards](https://www.ncsc.gov.uk/information/check-penetration-testing)
    * In step 10: when you complete the Service Desk Registration Form, send it to [api.management@nhs.net](mailto:api.management@nhs.net).
    * In step 11: submit your completed SCAL to [api.management@nhs.net](mailto:api.management@nhs.net).
    * In step 14: to request production access, contact us at [api.management@nhs.net](mailto:api.management@nhs.net).

    ## Endpoints
    To see details for specific endpoints, select from the list on the left hand side of the page:
    * `GET /Patient` - search for patients.
    * `GET /Patient/{id}` - get patient's personal details.
    * `GET /Patient/{id}/RelatedPerson` - get patient's related people details.
    * `PATCH /Patient/{id}` - update patient's personal details (coming soon).

  contact:
    name: Personal Demographics Service FHIR API Support
    url: 'https://tbc.api.nhs.net'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/personal-demographics'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/personal-demographics'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/personal-demographics'
    description: 'Production environment (not yet available: see "API status and roadmap").'
tags:
  - name: patients
  - name: relatedperson
paths:
  /Patient:
    parameters:
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/BearerAuthorization'
    get:
      summary: Search for patient
      operationId: search-patient
      externalDocs:
        description: ODS codes and documentation.
        url: https://digital.nhs.uk/services/organisation-data-service
      description: |
        ## Overview
        Use this endpoint to search for a patient in PDS.

        You can search using a combination of:
          * given name
          * family name
          * gender
          * postcode
          * date of birth (range)
          * date of death (range)
          * registered GP practice

        Ensure that the search parameters are url encoded, especially when containing special characters. For example a `space` must be represented by either `%20` or `+`.

        ## Matching rules
        Search parameters are not case sensitive.

        Spaces in postcodes do not need to match exactly, for example `LS116AD` will match `LS11 6AD`, however including spaces will also work.

        For date of birth and date of death, you can search for an exact date or for a range of dates.

        You can use wildcards in given name and family name. Wildcards must start with at least two characters; for example, `Br*` is valid, but `*cDougal` is not. Multiple wildcards are allowed; for example, `Br*w*` will match `Brown` and `Brower`.
        Be sure that any wildcards are encoded before sending the request. An encoded wildcard is `%2A`; for example, `Br%2A` is valid.

        You can request a fuzzy search using the `_fuzzy-match` query parameter. This will:
          * match common homophones, such as `Smith` and `Smythe`, using the [Soundex](https://en.wikipedia.org/wiki/Soundex) algorithm
          * check for transposed names, such as `Adam Thomas` and `Thomas Adam`

        Wildcards cannot be used with a fuzzy search.

        ## Search parameter options
        For a non-fuzzy search, the minimum set of search parameters is:
        * family name - but it can include wildcards
        * gender
        * date of birth - but it can be a range

        For a fuzzy search, use one of the following search parameter combinations:
        * given name, family name and date of birth
        * family name, date of birth, gender and postcode
        * given name, date of birth, gender and postcode

        If you include the date of death or registered GP Practice query parameters for a fuzzy search, they will not be used as part of the search. However they will affect the patient's matching score, meaning a mismatch will reduce the returned score.

        If you use an invalid combination of query parameters, you will get an `INVALID_COMBINATION` error.

        ## Historic data search
        By default the endpoint only searches current information.
        You can search historic information, such as previous names or addresses using the `_history` query parameter.

        You cannot perform a fuzzy search on historic information.

        ## Scoring
        Every matched patient in the result list includes a score to indicate how closely the patient matched the search parameters.

        A score of 1.0 indicates an exact match. A score of less than 1.0 indicates a partial match.

        The result list is sorted in descending score order - best match first.

        Use the `_exact-match` query parameter to return exact matches only - where the score is 1.0.

        ## Restricted patients
        Some patients are tagged as restricted, or sensitive. When performing a search, restricted patients can be returned; however, location sensitive fields such as `address`, `telecom` and `generalPractitioner` will be removed.

        If `address-postcode` or `general-practitioner` are included in the search parameters, no restricted patients will be returned even if a match is identified.

        The restricted flag can be found in the data under `meta/security` on the patient resource.

        NHS Digital guidance on restricting access to a patient's details can be found [here](https://digital.nhs.uk/services/demographics/restricting-access-to-a-patients-demographic-record)

        ## Number of results returned
        By default, the endpoint will return a maximum of 50 results.

        If there are more than 50 matching patients, the endpoint will return no results and the error response `TOO_MANY_MATCHES`.
        You can further limit the number of results using the `_max-results` query parameter.
        You can request a single, exact match using `_exact-match=true` and `_max-results=1`.

        ## Clinical safety and privacy
        This endpoint can return multiple matching patients for a given search, including partial matches.

        You should ensure that you design, build and test your software to minimise these risks:
        * an end user selects the wrong patient from the results presented, so there is a risk of clinical harm; for example due to retrieval of the wrong medical data
        * the end user has access to patients’ personal data, so there is a risk to patient privacy

        In particular, it is almost certainly a good idea to display search results in descending score order - best match first.

        ## Sandbox testing
        You can test the following scenarios in our sandbox environment:

        | Scenario                    | Request                                                      | Response                                   |
        | --------------------------- | ------------------------------------------------------------ | ------------------------------------------ |
        | Basic search                | `family`=`Smith`, `gender`=`female`, `birthdate`=`eq2010-10-22` | HTTP Status 200 with single search result. |
        | Wildcard search             | `family`=`Sm*`, `gender`=`female`, `birthdate`=`eq2010-10-22` | HTTP Status 200 with search result of two. |
        | Search with limited results | `family`=`Sm*`, `gender`=`female`, `birthdate`=`eq2010-10-22`, `_max-results`=`2` | HTTP Status 200 with search result of two. |
        | Search with date range      | `family`=`Smith`, `gender`=`female`, `birthdate`=`ge2010-10-21`, `birthdate`=`le2010-10-23` | HTTP Status 200 with single search result. |
        | Fuzzy search                | `family`=`Smith`, `given`=`Jane` `gender`=`female`, `birthdate`=`eq2010-10-22`, `_fuzzy-match`=`true` | HTTP Status 200 with single search result. |
        | Sensitive patient search    | `family`=`Smythe`, `given`=`Janet` `gender`=`female`, `birthdate`=`eq2005-06-16` | HTTP Status 200 with single search result without restricted data. |
        | Unsuccessful search         | Any other valid search query parameters                      | HTTP Status 200 with no search results     |
        | Invalid date format         | `birthdate` or `death-date` query parameters with values not in format `YYYY-MM-DD` | HTTP Status 400 with problem description   |
        | Too few search parameters   | Any invalid combination of query parameters                  | HTTP Status 400 with problem description   |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/dc052f444e70d072e577)
      tags:
        - patients
      parameters:
        - name: _exact-match
          description: The search only returns results where the `score` field is 1.0.
          example: true
          in: query
          required: false
          schema:
            type: boolean
            default: false
        - name: _history
          description: The search looks for matches in historic information such as previous names and addresses.
          example: true
          in: query
          required: false
          schema:
            type: boolean
            default: false
        - name: _fuzzy-match
          description: A fuzzy search is performed, including checks for homophones and transposed names.
          example: true
          in: query
          required: false
          schema:
            type: boolean
            default: false
        - name: _max-results
          description: The maximum number of results to return between 1 and 50. The default is 50.
          example: 1
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 50
        - name: family
          description: "The patient's family name (surname)."
          examples:
            simple:
              value: Smith
              summary: Will also match Smythe if `_fuzzy-match` is specified.
            wildcarded:
              value: "Sm*t*"
              summary: 'Wildcards must contain at least two characters, this will match Smith, Smythe'
          in: query
          required: false
          schema:
            type: string
        - name: given
          description: "The patient's given name."
          example: Jane
          in: query
          required: false
          schema:
            type: string
        - name: gender
          description: Gender with which the patient most strongly identifies.
          example: female
          in: query
          required: false
          schema:
            type: string
            enum:
              - male
              - female
              - other
              - unknown
            example: female
        - name: birthdate
          in: query
          description: Date of birth in the format `<eq|ge|le>yyyy-mm-dd`. To specify a range, use `birthdate=geyyyy-mm-dd&birthdate=leyyyy-mm-dd`.
          examples:
            simple:
              value: eq2010-10-22
              description: Exact match date
            rangege:
              value: 'ge2010-10-22'
              description: Greater than or equals match, which matches 2010-10-22 or 2010-10-23
            rangele:
              value: 'le2010-10-22'
              description: Less than or equals match, which matches 2010-10-22 or 2010-10-21
          required: false
          schema:
            type: array
            items:
              type: string
        - name: death-date
          in: query
          description: Date of death in the format `<eq|ge|le>yyyy-mm-dd`. To specify a range, use `death-date=geyyyy-mm-dd&death-date=leyyyy-mm-dd`.
          examples:
            simple:
              value: eq2010-10-22
              description: Exact match date
            rangege:
              value: ge2010-10-22
              description: Greater than or equals match which matches 2010-10-22 or 2010-10-23
            rangele:
              value: 'le2010-10-22'
              description: Less than or equals match, which matches 2010-10-22 or 2010-10-21
          required: false
          schema:
            type: string
            format: date
        - name: address-postcode
          description: The postcode of any of the patient’s known addresses. White spaces in postcodes are not significant; that is, LS16AE and LS1 6AE will both match LS1 6AE.
          examples:
            simple:
              value: LS1 6AE
              summary: 'Spaces not important, would match LS16AE'
            wildcarded:
              value: "LS1*"
              summary: "Will match 'LS16AE', 'LS1 6AE' and 'LS1 6AB'"
          in: query
          required: false
          schema:
            type: string
        - name: general-practitioner
          description: "The Organisation Data Service (ODS) code of the patient's registered GP practice."
          example: Y00001
          in: query
          required: false
          schema:
            type: string
            format: ods_code
      responses:
        '200':
          description: 'A completed search, containing zero, one, or many matching patients.'
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    description: FHIR Resource Type.
                    default: Bundle
                  type:
                    type: string
                    description: FHIR Bundle Type.
                    default: searchset
                  timestamp:
                    type: string
                    description: Time the search was performed.
                    format: datetime
                    example: '2019-12-25T12:00:00+00:00'
                  total:
                    type: integer
                    description: Number of resources returned in search.
                    example: 1
                  entry:
                    type: array
                    description: |
                      A list of matched patients. Empty if none found. The patients are ordered by match score, best first. A maximum of 50 patients will be returned.
                    items:
                      type: object
                      properties:
                        fullUrl:
                          type: string
                          description: Absolute URL of the resource described in this item.
                          example: 'https://beta.api.digital.nhs.uk/personal-demographics/Patient/9000000009'
                        search:
                          type: object
                          properties:
                            score:
                              description: Search score from 0.0 to 1.0.
                              type: number
                              minimum: 0.0
                              maximum: 1.0
                              example: 0.75
                        resource:
                          $ref: 'components/schemas/PatientSearch.yaml'
              example:
                resourceType: Bundle
                type: searchset
                timestamp: '2019-12-25T12:00:00+00:00'
                total: 1
                entry:
                  - fullUrl: 'https://beta.api.digital.nhs.uk/personal-demographics/Patient/9000000009'
                    search:
                      score: 1
                    resource:
                      $ref: components/examples/PatientSearch.json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                not-enough:
                  summary: too few search params
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_SEARCH_DATA
                              display: Invalid search data provided - Not enough search parameters were provided to be able to make a search.
                bad-combination:
                  summary: Invalid combination of search parameters
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_SEARCH_DATA
                              display: Invalid search data provided - 'Invalid Date Combination'
  '/Patient/{id}':
    parameters:
      - $ref: '#/components/parameters/Id'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/BearerAuthorization'
    get:
      description: |
        ## Overview
        Use this endpoint to get patient details from PDS for a given NHS Number.

        ## Superceded patients
        Some patients are marked as superceded, this means that for some reason the original resource is no longer valid and has been replaced with a different resource.

        On retrieval of a superceded resource the new resource will be automatically returned in place of the requested resource.

        ## Restricted patients
        Some patients are tagged as restricted, or sensitive. Restricted patients can be retrieved; however, location sensitive fields such as `address`, `telecom` and `generalPractitioner` will be removed.

        The restricted flag can be found in the data under `meta/security` on the patient resource.

        NHS Digital guidance on restricting access to a patient's details can be found [here](https://digital.nhs.uk/services/demographics/restricting-access-to-a-patients-demographic-record)

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:

        | Scenario                 | Request                                           | Response                                                                       |
        | ------------------------ | ------------------------------------------------- | ------------------------------------------------------------------------------ |
        | Patient exists           | `id`=`9000000009`                                 | HTTP Status 200 with patient data in response                                  |
        | Sensitive patient exists | `id`=`9000000025`                                 | HTTP Status 200 with patient data in response with the restricted data removed |
        | Patient doesn't exist    | `id`=`9111231130` (or any other valid NHS Number) | HTTP Status 404 with problem description                                       |
        | Invalid NHS Number       | `id`=`9000000000` (or any invalid NHS Number)     | HTTP Status 400 with problem description                                       |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/dc052f444e70d072e577)
      summary: "Retrieve a patient's record"
      operationId: get-patient
      tags:
        - patients
      responses:
        '200':
          description: Information successfully returned.
          headers:
            ETag:
              $ref: components/schemas/ETag.yaml
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/Patient.yaml
              example:
                $ref: components/examples/Patient.json
        '400':
          description: Invalid NHS number supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: INVALID_RESOURCE_ID
                          display: Resource Id is invalid
        '404':
          description: Patient not found.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: not-found
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: RESOURCE_NOT_FOUND
                          display: Resource not found
    patch:
      description: |
        ## Overview
        Use this endpoint to update patient details in PDS.

        This is a 'patch' operation, meaning you can update specific parts of the patient record (such as a name or an address), as opposed to having to update the entire record.

        ## Patient record versioning
        To update a patient's record you must have retrieved it first.
        When you retrieve a patient record, you get a version number for the record (in the `ETag` header and in the `versionId` field in the response).
        You must then pass the record's version number in the update request (in the `If-Match` header).
        The update will only succeed if the patient record has not been updated in our database in the meantime.
        If the update succeeds, you will receive a copy of the update record in the response, including the new record version number.
        If you have a subsequent update you must use the new version number.

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment.
        Note that your changes will not be persisted.
        JSON Patch operations themselves are validated, but the resulting resource is not validated for correctness.

        | Scenario                            | Request                                                      | Response                                         |
        | ----------------------------------- | ------------------------------------------------------------ | ------------------------------------------------ |
        | Successful update                   | `id`=`9000000009`<br />Body: One of the provided examples<br />Headers: `If-Match`=`W/"2"`, `Content-Type`=`application/json-patch+json` | HTTP Status 200 with updated patient in response (but note that the update won't be persisted) |
        | Patient doesn't exist               | `id`=`9111231130` (or any other valid NHS Number)            | HTTP Status 404 with problem description         |
        | Invalid NHS Number                  | `id`=`9000000000` (or any invalid NHS Number)                | HTTP Status 400 with problem description         |
        | Missing resource version identifier | `If-Match` header missing or set to format other than `W/"<version>"` | HTTP Status 400 with problem description         |
        | Incorrect resource version          | `If-Match`=`W/"1"`                                           | HTTP Status 412 with problem description         |
        | Wrong content type                  | `Content-Type` header missing or other than `application/json-patch+json` | HTTP Status 415 with problem description         |
        | No patches sent                     | Send body with no `patches` attribute                        | HTTP Status 400 with problem description         |
        | Invalid patch operation(s)          | Send body with invalid JSON patches in `patches` attribute   | HTTP Status 400 with problem description         |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/dc052f444e70d072e577)


      summary: Update a patient's record
      operationId: update-patient-partial
      tags:
        - patients
      externalDocs:
        description: IETF RFC 6902, which defines json-patch.
        url: https://tools.ietf.org/html/rfc6902
      parameters:
        - $ref: '#/components/parameters/IfMatch'
      requestBody:
        required: true
        content:
          # application/json-patch+json: FIXME - should be set to this but we have had to change it due to an Apigee SmartDocs bug.
          # See email chain w subject "Try this API feature for PATCH/POST APIs" between Alex H, Tony H, and David Macdonald from Apigee
          application/json:
            schema:
              type: object
              required:
                - patches
              properties:
                correction:
                  description: Set to true if the update is correcting previously incorrect data.
                  type: boolean
                  default: false
                patches:
                  $ref: components/schemas/JsonPatch.yaml
            examples:
              add-name:
                summary: Add a new name to the patient
                value:
                  $ref: components/examples/requests/PatientPatch/add-name.json
              update-name:
                summary: Update the first given name entry
                value:
                  $ref: components/examples/requests/PatientPatch/update-name.json
              delete-name:
                summary: Remove a name no longer in use
                value:
                  $ref: components/examples/requests/PatientPatch/delete-name.json
      responses:
        '200':
          description: Patient updated.
          headers:
            ETag:
              $ref: components/schemas/ETag.yaml
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/Patient.yaml
        '400':
          description: Client error.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                invalid-nhs-number:
                  summary: Invalid NHS number supplied
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_RESOURCE_ID
                              display: Resource Id is invalid
                no-patches-submitted:
                  summary: No patches submitted
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: MISSING_VALUE
                              display: Missing value - patches
                invalid-patch-operation:
                  summary: Invalid patch operation(s)
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_UPDATE
                              display: Invalid update with error - Invalid payload received - incorrect format
        '404':
          description: Patient not found.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: not-found
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: RESOURCE_NOT_FOUND
                          display: Resource not found
        '412':
          $ref: '#/components/responses/412PreconditionFailed'

  '/Patient/{id}/RelatedPerson':
    parameters:
      - $ref: '#/components/parameters/Id'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/BearerAuthorization'
    get:
      description: |
        ## Overview
        Use this endpoint to get a patient's related people details from PDS for a given NHS Number. This is a list of people who can be contacted, and how, regarding the patient. These details may be useful for a practitioner to get in contact with a next of kin or guardian.
        
        ## Restricted patients
        Some patients are tagged as restricted, or sensitive. Related people will not be returned for a restricted patient and an empty bundle will be returned.

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:

        | Scenario                        | Request                                       | Response                                                      |
        | ------------------------------- | --------------------------------------------- | ------------------------------------------------------------- |
        | Multiple related people exists  | `id`=`9000000009`                             | HTTP Status 200 with related person data in a response Bundle |
        | Single related person exists    | `id`=`9000000017`                             | HTTP Status 200 with related person data in a response Bundle |
        | Related people do not exist     | `id`=`9000000025`                             | HTTP Status 404 with problem description                      |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/dc052f444e70d072e577)
      summary: "Retrieve a list of Related Person resources for a given patient"
      operationId: get-related-people
      tags:
        - relatedperson
      responses:
        '200':
          description: Information successfully returned.
          headers:
            ETag:
              $ref: components/schemas/ETag.yaml
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    description: FHIR Resource Type.
                    default: Bundle
                  type:
                    type: string
                    description: FHIR Bundle Type.
                    default: searchset
                  timestamp:
                    type: string
                    description: Time the search was performed.
                    format: datetime
                    example: '2019-12-25T12:00:00+00:00'
                  total:
                    type: integer
                    description: Number of resources returned in search.
                    example: 1
                  entry:
                    type: array
                    description: |
                      A list of related people details attached to the patient. 
                    items:
                      type: object
                      properties:
                        fullUrl:
                          type: string
                          description: Absolute URL of the resource described in this item.
                          example: 'https://beta.api.digital.nhs.uk/personal-demographics/Patient/9000000009/RelatedPerson/507B7621'
                        resource:
                          $ref: components/schemas/RelatedPerson.yaml
              example:
                resourceType: Bundle
                type: searchset
                timestamp: '2019-12-25T12:00:00+00:00'
                total: 1
                entry:
                  - fullUrl: 'https://beta.api.digital.nhs.uk/personal-demographics/Patient/9000000009/RelatedPerson/507B7621'
                    resource:
                      $ref: components/examples/RelatedPerson.json
        '400':
          description: Invalid NHS number supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: INVALID_RESOURCE_ID
                          display: Resource Id is invalid
        '404':
          description: Related People not found.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: not-found
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: RESOURCE_NOT_FOUND
                          display: Resource not found

components:
  parameters:
    Id:
      name: id
      in: path
      description: The patient's NHS Number. The primary identifier of a patient, unique within NHS England and Wales. Always 10 digits and must be a [valid NHS Number](https://www.datadictionary.nhs.uk/data_dictionary/attributes/n/nhs/nhs_number_de.asp).
      required: true
      schema:
        type: string
        example: "9000000009"
    ObjectId:
      name: object_id
      in: path
      description: A resource Object ID. The primary identifier of a resource.
      required: true
      schema:
        type: string
        example: "507B7621"
    IfMatch:
      in: header
      name: If-Match
      description: |
        Latest known version identifier enclosed in quotes preceded by `W/`.

        Send the value of this resource's `ETag` response header (or `meta.versionId` property) as received.
      required: true
      schema:
        type: string
        format: "^W\\/\\\"[[:print:]]+\\\"$"  # Printable characters enclosed in quotes. See: https://tools.ietf.org/html/rfc7230#section-3.2.6
        example: 'W/"2"'
    RoleId:
      in: header
      name: NHSD-Session-URID
      description: |
        A User Role ID (URID), also known as a User Role Profile ID (URPID), specifies the role the user is acting in. This dictates the actions they can perform.

        A URID belongs to a user (they are not generic) and a user may have more than one.

        Note: This parameter is required unless interacting with the Sandbox.
      required: false
      schema:
        type: string
        format: '^[0-9]+$'
        example: '555021935107'
    BearerAuthorization:
      in: header
      name: Authorization
      description: |
        An OAuthV2 access token presented in Bearer format.

        Note: This parameter is required unless interacting with the Sandbox.
      required: false
      schema:
        type: string
        format: '^Bearer\ [[:ascii:]]+$'
        example: 'Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM'
  schemas:
    Patient:
      $ref: components/schemas/Patient.yaml
    PatientSearch:
      $ref: components/schemas/PatientSearch.yaml
    RelatedPerson:
      $ref: components/schemas/RelatedPerson.yaml
    OperationOutcome:
      $ref: components/schemas/OperationOutcome.yaml
  responses:
    412PreconditionFailed:
      description: |
        Precondition failed.

        The version identifier submitted in the `If-Match` header was not the latest version of the resource.
      content:
        application/fhir+json:
          schema:
            $ref: components/schemas/OperationOutcome.yaml
          examples:
            invalid-if-match:
              summary: Invalid If-Match header
              value:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: conflict
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: PRECONDITION_FAILED
                          display: Invalid update with error - This resource has changed since you last read. Please re-read and try again with the new version number.
            missing-if-match:
              summary: Missing If-Match header
              value:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: required
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: PRECONDITION_FAILED
                          display: Invalid update with error - If-Match header must be supplied to update this resource

